name: flutter_state_management_all_in_one
description: "Best state management package in flutter? Let's try them all and see!"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  itrie:
    path: ./packages/itrie

  # bloc
  flutter_bloc: ^8.1.3
  meta: ^1.10.0

  # riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # signals
  signals: ^2.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # riverpod
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - assets/words.txt
